# Generated by Django 5.0.10 on 2024-12-25 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('NSS', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('DateDeNaissonce', models.DateField()),
                ('Adress', models.CharField(max_length=45)),
                ('Numero', models.CharField(max_length=20)),
                ('Mutuelle', models.CharField(blank=True, max_length=45, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('ContactNom', models.CharField(max_length=20)),
                ('ContactNumero', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='DPI_Patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
