# Generated by Django 5.0.10 on 2024-12-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ordonnance', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('IdMedicament', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentOrdonnance',
            fields=[
                ('IdMedicamentOrdonnance', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.FloatField()),
                ('duree', models.IntegerField()),
                ('Medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='Medicaments.medicament')),
                ('Ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='Ordonnance.ordonnance')),
            ],
        ),
    ]
