# Generated by Django 5.0.10 on 2024-12-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='infermier',
            field=models.ForeignKey(limit_choices_to={'role': 'infirmier'}, on_delete=django.db.models.deletion.CASCADE, related_name='Soin_infirmier', to=settings.AUTH_USER_MODEL),
        ),
    ]
