# Generated by Django 5.0.10 on 2024-12-26 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consultation', '0002_remove_consultation_nss_consultation_idconsultation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeBilan',
            fields=[
                ('IdDemandeBilan', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Type', models.CharField(choices=[('Biologique', 'Biologique'), ('Radiologique', 'Radiologique')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('IdBilanBiologique', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parametre', models.CharField(choices=[('Hemogramme', 'Hemogramme'), ('Glycemie', 'Glycemie'), ('Cholesterol', 'Cholesterol'), ('Creatinine', 'Creatinine'), ('Uree', 'Uree'), ('Bilirubine', 'Bilirubine'), ('Transaminases', 'Transaminases'), ('Protides', 'Protides'), ('CRP', 'CRP'), ('TSH', 'TSH'), ('PSA', 'PSA'), ('Ferritine', 'Ferritine'), ('Fer', 'Fer')], max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BilanBiologique_Consultation', to='Consultation.consultation')),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'laborantin'}, on_delete=django.db.models.deletion.CASCADE, related_name='BilanBiologique_Medecin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('IdBilanRadiologique', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examen', models.CharField(choices=[('Radio', 'Radio'), ('Echographie', 'Echographie'), ('IRM', 'IRM'), ('Scanner', 'Scanner'), ('Mammographie', 'Mammographie'), ('Densitometrie', 'Densitometrie'), ('Endoscopie', 'Endoscopie'), ('Electrocardiogramme', 'Electrocardiogramme'), ('HolterECG', 'HolterECG'), ('HolterTA', 'HolterTA'), ('EchoCardio', 'EchoCardio'), ('Scintigraphie', 'Scintigraphie'), ('Angiographie', 'Angiographie'), ('Arthroscanner', 'Arthroscanner'), ('ArthroIRM', 'ArthroIRM'), ('Arthrographie', 'Arthrographie'), ('Uroscanner', 'Uroscanner'), ('UroIRM', 'UroIRM'), ('Urographie', 'Urographie'), ('Mammographie', 'Mammographie'), ('Mammographie', 'Mammographie'), ('Mammographie', 'Mammographie')], max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BilanRadiologique_Consultation', to='Consultation.consultation')),
                ('Medecin', models.ForeignKey(limit_choices_to={'role': 'radiologue'}, on_delete=django.db.models.deletion.CASCADE, related_name='BilanRadiologique_Medecin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
