# Generated by Django 5.0.10 on 2024-12-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bilan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanbiologique',
            old_name='medecin',
            new_name='laborantin',
        ),
        migrations.RenameField(
            model_name='bilanradiologique',
            old_name='Medecin',
            new_name='radiologue',
        ),
    ]
