# Generated by Django 5.0.10 on 2024-12-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bilan', '0002_rename_medecin_bilanbiologique_laborantin_and_more'),
        ('Consultation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebilan',
            name='Consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Demande_Consultation', to='Consultation.consultation'),
        ),
        migrations.AlterField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(limit_choices_to={'role': 'laborantin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BilanBiologique_Laborantin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(limit_choices_to={'role': 'radiologue'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BilanRadiologique_Radiologue', to=settings.AUTH_USER_MODEL),
        ),
    ]
