# Generated by Django 5.0.10 on 2024-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bilan', '0003_demandebilan_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanradiologique',
            name='compterendu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
