# Generated by Django 5.0.10 on 2024-12-12 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSS', models.BigIntegerField(unique=True)),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('DateDeNaissonce', models.DateField()),
                ('Adress', models.CharField(max_length=45)),
                ('Numero', models.CharField(max_length=20)),
                ('Mutuelle', models.CharField(blank=True, max_length=45, null=True)),
                ('ContactNom', models.CharField(max_length=20)),
                ('ContactNumero', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=20)),
                ('DPI_NSS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi', to_field='NSS')),
            ],
        ),
    ]
