# Generated by Django 5.0.10 on 2024-12-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='sexe',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='mo_hamza@esi.dz', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
