# Generated by Django 5.0.10 on 2024-12-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0002_dpi_sexe_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Medcin', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Resume', models.TextField()),
                ('Diagnostic', models.CharField(max_length=100)),
                ('Traitement', models.CharField(max_length=100)),
                ('DPI_NSS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi', to_field='NSS')),
            ],
        ),
    ]
