# Generated by Django 5.0.10 on 2024-12-28 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DPI', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('IdConsultation', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('DPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consultation_DPI', to='DPI.dpi')),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='Consultation_Medecin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
