# Generated by Django 5.0.10 on 2024-12-25 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('NSS', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('DPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consultation_DPI', to='DPI.dpi')),
                ('Medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='Consultation_Medecin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
