# Generated by Django 5.0.10 on 2024-12-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='NSS',
        ),
        migrations.AddField(
            model_name='consultation',
            name='IdConsultation',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
